// Full RU -> EN dictionary for DOM-level translation.
export const EN = {
  // nav / shell
  'Каталог': 'Catalog', 'Карта': 'Map', 'ИИ-агент': 'AI Agent', 'Подбор': 'Recommendations',
  'Избранное': 'Favorites', 'Сообщения': 'Messages', 'Кабинет': 'Dashboard', 'Модерация': 'Moderation',
  'Войти': 'Sign in', 'Регистрация': 'Sign up', 'Профиль': 'Profile', 'Выйти': 'Log out',
  'История просмотров': 'Viewing history', 'Мои брони': 'My bookings', 'Трекеры цен': 'Price trackers',
  'Заявки': 'Requests', 'Уведомления': 'Notifications', 'Прочитать все': 'Mark all read',
  'Уведомлений пока нет': 'No notifications yet', 'Кабинет продавца': 'Seller dashboard', 'Тема': 'Theme',
  'Без имени': 'No name',
  // footer
  'Продукт': 'Product', 'Компания': 'Company', 'Поддержка': 'Support', 'О проекте': 'About',
  'Документация API': 'API docs', 'Связаться': 'Contact', 'Все права защищены': 'All rights reserved',
  'Иммерсивный AI-маркетплейс недвижимости': 'Immersive AI real estate marketplace',
  // catalog / home
  'Каталог недвижимости': 'Property catalog', 'Найдено объектов': 'Properties found', 'Загрузка...': 'Loading...',
  'Найдите дом, в который захочется вернуться': 'Find a home worth coming back to',
  'Иммерсивные 360°-туры, ответы ИИ про любую зону квартиры и честные сделки онлайн.': 'Immersive 360° tours, AI answers about any zone of the home, and fair deals online.',
  'Поиск: «двушка у метро», адрес, район...': 'Search: "2-bed near metro", address, area...',
  'Искать': 'Search', 'Виртуальные туры': 'Virtual tours', 'Комиссия за просмотр': 'Viewing fee',
  'Все': 'All', 'Любой тип': 'Any type', 'Комнаты': 'Rooms', 'Цена от': 'Price from', 'до': 'to',
  'Площадь от': 'Area from', 'Сбросить': 'Reset', 'Ничего не найдено': 'Nothing found',
  'Попробуйте изменить фильтры': 'Try changing the filters', 'Показать ещё': 'Show more',
  'Результаты поиска': 'Search results', 'Аренда': 'Rent', 'Продажа': 'Sale',
  'Квартира': 'Apartment', 'Дом': 'House', 'Коммерция': 'Commercial', 'Адрес не указан': 'Address not specified',
  'Все сделки': 'All deals', 'Все типы': 'All types', '360° тур': '360° tour', 'ночь': 'night', '/ ночь': '/ night',
  // property
  'Назад': 'Back', 'Объект не найден': 'Property not found', 'В каталог': 'To catalog',
  'Описание': 'Description', 'AI-оценка': 'AI review', 'История цен': 'Price history', 'Ипотека': 'Mortgage',
  'Отзывы': 'Reviews', 'Доступность': 'Availability', 'Похожие': 'Similar', 'Описание отсутствует.': 'No description.',
  'Правила дома': 'House rules', 'Динамика цены': 'Price dynamics', 'История цен пока недоступна.': 'Price history is not available yet.',
  'Рыночный контекст': 'Market context', 'Медиана рынка': 'Market median', 'Средняя по рынку': 'Market average',
  'Похожих объектов': 'Comparables', 'Похожих объектов пока нет.': 'No similar properties yet.',
  'Выгодно': 'Great deal', 'Справедливо': 'Fair', 'Завышено': 'Overpriced', 'Подозрительно': 'Suspicious',
  'Вероятно скам': 'Likely scam', 'Мало данных': 'Insufficient data', 'Оценка ИИ': 'AI verdict', 'Эвристика': 'Heuristic',
  'Плюсы': 'Pros', 'Минусы': 'Cons', 'Красные флаги': 'Red flags', 'Риск скама': 'Scam risk',
  'Не удалось получить оценку.': 'Could not get the review.',
  'Ипотечный калькулятор': 'Mortgage calculator', 'Первый взнос, $': 'Down payment, $', 'Ставка, %': 'Rate, %',
  'Срок, лет': 'Term, years', 'Рассчитать': 'Calculate', 'Сумма кредита': 'Loan amount',
  'Платёж / мес': 'Monthly payment', 'Всего выплат': 'Total paid', 'Переплата': 'Total interest',
  'Оставить отзыв': 'Write a review', 'Отзывов пока нет. Будьте первым!': 'No reviews yet. Be the first!',
  'Отзывов пока нет.': 'No reviews yet.', 'Ваш отзыв': 'Your review', 'Оценка': 'Rating', 'Комментарий': 'Comment',
  'Опубликовать': 'Publish', 'Поделитесь впечатлениями...': 'Share your impressions...', 'Спасибо за отзыв!': 'Thanks for your review!',
  'Доступные периоды': 'Available periods', 'Владелец пока не указал доступные даты.': 'The owner has not set available dates yet.',
  'Тип сделки': 'Deal type', 'Тип': 'Type', 'Площадь': 'Area', 'Комнат': 'Rooms', 'Цена за м²': 'Price per m²',
  'Просмотров': 'Views', 'Рейтинг': 'Rating', 'Рейтинг продавца': 'Seller rating', 'Нет отзывов': 'No reviews', 'Открыть 360° тур': 'Open 360° tour', 'Забронировать': 'Book now',
  'Заявка на просмотр': 'Request a viewing', 'Связаться с риелтором': 'Contact realtor', 'В избранное': 'Add to favorites',
  'В избранном': 'In favorites', 'Отслеживать цену': 'Track price', 'Пожаловаться на продавца': 'Report seller',
  'Управлять (в кабинете)': 'Manage (in dashboard)', 'Продавец': 'Seller', 'Администратор': 'Administrator',
  'Покупатель': 'Buyer', 'Пользователь': 'User', 'по арендам этого продавца': 'rental reviews of this seller',
  'по объектам этого продавца': 'reviews of this seller', 'Бронь и оплата онлайн за пару кликов': 'Booking and payment online in a couple clicks',
  'Заезд': 'Check-in', 'Выезд': 'Check-out', 'Выберите даты': 'Select dates', 'Перейти к оплате': 'Proceed to payment',
  'Оплата брони': 'Booking payment', 'Бронь создана — оплатите в открывшемся окне': 'Booking created — pay in the opened window',
  'Сообщение': 'Message', 'Здравствуйте! Хочу посмотреть объект...': 'Hello! I would like to view this property...',
  'Желаемая дата': 'Preferred date', 'Отправить заявку': 'Send request', 'Заявка отправлена!': 'Request sent!',
  'Начать диалог': 'Start chat', 'Диалог создан': 'Chat created', 'Здравствуйте!': 'Hello!',
  'Здравствуйте! Интересует ваш объект...': 'Hello! I am interested in your property...',
  'Здравствуйте! Интересуют ваши объекты...': 'Hello! I am interested in your listings...',
  'Трекер цены': 'Price tracker', 'Уведомим, когда цена упадёт. Можно указать целевую цену.': 'We will notify you when the price drops. You can set a target price.',
  'Уведомим, когда цена упадёт': 'We will notify you when the price drops', 'Целевая цена, $': 'Target price, $',
  'Отслеживать': 'Track', 'Трекер добавлен': 'Tracker added', 'Жалоба на продавца': 'Report a seller',
  'Причина': 'Reason', 'Опишите проблему...': 'Describe the problem...', 'Отправить жалобу': 'Submit complaint',
  'Опишите причину': 'Describe the reason', 'Жалоба отправлена': 'Complaint submitted',
  // tour
  'Тур недоступен': 'Tour unavailable', 'К объекту': 'To property', 'Спросить про зону': 'Ask about a zone',
  'Отменить': 'Cancel', 'Поделиться': 'Share', 'Перейти': 'Go', 'Ваш вопрос': 'Your question',
  'Вопрос про выделенную зону. Ответит ИИ (vision), это займёт несколько секунд.': 'A question about the selected zone. The AI (vision) will answer in a few seconds.',
  'Например: из какого материала эта стена?': 'E.g.: what material is this wall?', 'Спросить ИИ': 'Ask AI',
  'Введите вопрос': 'Enter a question', 'ИИ анализирует зону...': 'AI is analyzing the zone...',
  'Ответ ИИ': 'AI answer', 'Не удалось получить ответ.': 'Could not get an answer.',
  'Превышено время ожидания.': 'Request timed out.', 'Ссылка скопирована': 'Link copied', 'Не удалось поделиться': 'Could not share',
  // messages
  'Выберите диалог': 'Select a chat', 'Начните общение с риелтором со страницы объекта': 'Start chatting with a realtor from a property page',
  'Диалогов пока нет': 'No chats yet', 'Нет сообщений': 'No messages', 'Напишите сообщение...': 'Type a message...',
  'Прикрепить файл': 'Attach file', 'Ответить': 'Reply', 'Изменить': 'Edit', 'Удалить': 'Delete',
  'Сообщение удалено': 'Message deleted', 'Загрузка файла...': 'Uploading file...', 'Файл': 'File',
  'изменено': 'edited', 'вложение': 'attachment', 'Редактирование': 'Editing', 'Ответ': 'Reply',
  // agent
  'ИИ-агент Nestora': 'Nestora AI Agent', 'Ищет, сравнивает и управляет объектами за вас через реальные инструменты': 'Searches, compares and manages properties for you via real tools',
  'Новый чат': 'New chat', 'Спросите что угодно про недвижимость...': 'Ask anything about real estate...',
  'Найди квартиру в аренду до $300 за ночь': 'Find an apartment to rent under $300 a night',
  'Покажи дома на продажу до $800k': 'Show houses for sale under $800k', 'Что у меня в избранном?': 'What is in my favorites?',
  'Сравни объекты 1 и 2': 'Compare properties 1 and 2', 'Посоветуй по ипотеке на 20 лет': 'Advise on a 20-year mortgage',
  'Новый чат начат. Чем помочь?': 'New chat started. How can I help?', '(пустой ответ)': '(empty reply)',
  'поиск объектов': 'search', 'открыть тур': 'open tour', 'на карте': 'on map', 'сравнение': 'compare',
  'избранное': 'favorites', 'в избранное': 'add favorite', 'история': 'history', 'очистка истории': 'clear history',
  'трекер цены': 'price tracker', 'рекомендации': 'recommendations',
  // personal
  'Сохранённые объекты': 'Saved properties', 'Очистить всё': 'Clear all', 'Очистить избранное?': 'Clear favorites?',
  'Избранное очищено': 'Favorites cleared', 'Избранное пусто': 'Favorites is empty',
  'Добавляйте понравившиеся объекты сердечком': 'Add properties you like with the heart',
  'Объекты, которые вы недавно открывали': 'Properties you recently opened', 'Очистить': 'Clear', 'Очистить историю?': 'Clear history?',
  'История очищена': 'History cleared', 'История пуста': 'History is empty', 'Открывайте объекты, и они появятся здесь': 'Open properties and they will appear here',
  'Подбор для вас': 'Picked for you', 'Рекомендации на основе вашей истории и избранного': 'Recommendations based on your history and favorites',
  'Подсказка ИИ: например «для семьи с детьми»': 'AI hint: e.g. "for a family with kids"', 'Подобрать с ИИ': 'Pick with AI',
  'С объяснением от ИИ': 'With AI explanation', 'По вашим интересам': 'Based on your interests',
  'Пока нет рекомендаций': 'No recommendations yet', 'Посмотрите несколько объектов, чтобы ИИ понял ваши вкусы': 'View a few properties so the AI learns your taste',
  'Нет данных': 'No data', 'Обновить': 'Refresh', 'Перевести': 'Translate', 'Оригинал': 'Original',
  'Уже на русском': 'Already in Russian', 'Страница': 'Page', 'Далее': 'Next',
  'Показать ещё отзывы': 'Show more reviews', 'Мои бронирования': 'My bookings', 'Аренда и статусы оплаты': 'Rentals and payment status',
  'Броней пока нет': 'No bookings yet', 'Забронируйте жильё из каталога аренды': 'Book a place from the rental catalog',
  'Ожидает оплаты': 'Awaiting payment', 'Подтверждено': 'Confirmed', 'Отменено': 'Cancelled', 'Не оплачено': 'Unpaid',
  'Оплачено': 'Paid', 'Возврат': 'Refunded', 'Оплатить (тест)': 'Pay (test)', 'Отменить бронь?': 'Cancel booking?',
  'Бронь отменена': 'Booking cancelled', 'Оплачено!': 'Paid!', 'Нет активных трекеров': 'No active trackers',
  'Добавьте трекер со страницы объекта': 'Add a tracker from a property page', 'Убрать': 'Remove', 'Трекер удалён': 'Tracker removed',
  'любое падение': 'any drop', 'Заявки на просмотр': 'Viewing requests', 'Заявки на просмотр ваших объектов': 'Viewing requests for your properties',
  'Ваши заявки на просмотр': 'Your viewing requests', 'Заявок нет': 'No requests', 'Управление аккаунтом': 'Account settings',
  'Email подтверждён': 'Email verified', 'Email не подтверждён': 'Email not verified', 'Сменить фото': 'Change photo',
  'Имя': 'Name', 'Телефон': 'Phone', 'Компания / агентство': 'Company / agency', 'Профиль сохранён': 'Profile saved',
  'Безопасность': 'Security', 'Сменить пароль': 'Change password', 'Опасная зона': 'Danger zone',
  'Личные данные': 'Personal details', 'Мой публичный профиль': 'My public profile',
  'Пароль и доступ к аккаунту.': 'Password and account access.', 'ИИ-агент': 'AI Agent',
  'Спросите про недвижимость...': 'Ask about real estate...', 'Очистить историю': 'Clear history',
  'История очищена': 'History cleared', 'Свернуть': 'Minimize', 'ИИ не настроен на сервере.': 'AI is not configured on the server.',
  'Удаление аккаунта необратимо.': 'Account deletion is irreversible.', 'Удалить аккаунт': 'Delete account',
  'Удалить аккаунт? Это необратимо.': 'Delete account? This is irreversible.', 'Аккаунт удалён': 'Account deleted',
  'Аватар обновлён': 'Avatar updated', 'Смена пароля': 'Change password', 'Текущий пароль': 'Current password',
  'Новый пароль': 'New password', 'Сменить': 'Change', 'Пароль изменён. Войдите заново.': 'Password changed. Please sign in again.',
  // dashboard
  'Ваши объекты и аналитика': 'Your properties and analytics', 'Новый объект': 'New property', 'Объектов': 'Properties',
  'Активных': 'Active', 'С 360°-туром': 'With 360° tour', 'Объектов пока нет': 'No properties yet',
  'Создайте первое объявление': 'Create your first listing', 'Активно': 'Active', 'На паузе': 'Paused', 'Удалено': 'Deleted',
  'Аналитика': 'Analytics', 'Тур': 'Tour', 'Пауза': 'Pause', 'Активировать': 'Activate', 'Удалить объект?': 'Delete property?',
  'Самые обсуждаемые зоны': 'Most discussed zones', 'Без комнаты': 'No room', 'Редактировать объект': 'Edit property',
  'Заголовок': 'Title', 'Сделка': 'Deal', 'Срок аренды': 'Rent term', 'Краткосрочно': 'Short-term', 'Долгосрочно': 'Long-term',
  'Цена/ночь, $': 'Price/night, $', 'Цена, $': 'Price, $', 'Площадь, м²': 'Area, m²', 'Адрес': 'Address',
  'Координаты можно не указывать — определим по адресу (Mapbox).': 'Coordinates are optional — we geocode the address (Mapbox).',
  'Фото и 360°-панорамы': 'Photos and 360° panoramas', 'Добавить фото': 'Add photo', 'Добавить 360°': 'Add 360°',
  'Объект опубликован': 'Property published', 'Объект обновлён': 'Property updated', 'Введите заголовок (мин. 3)': 'Enter a title (min. 3)',
  'Укажите цену': 'Enter a price', 'Укажите площадь': 'Enter an area', 'Сохранить тур': 'Save tour',
  'Каждая комната — панорама. Переходы между комнатами работают как стрелки в Google Street View.': 'Each room is a panorama. Transitions work like Street View arrows.',
  'Комната': 'Room', 'Стартовая': 'Start', 'Название': 'Name', 'Панорама (URL или загрузка)': 'Panorama (URL or upload)',
  'URL панорамы': 'Panorama URL', 'Переходы (стрелки в др. комнаты)': 'Transitions (arrows to other rooms)',
  'метка': 'label', 'переход': 'transition', 'Добавить комнату': 'Add room', 'Тур сохранён': 'Tour saved',
  'Добавьте хотя бы одну комнату': 'Add at least one room', 'У каждой комнаты должны быть ID и панорама': 'Each room needs an ID and a panorama',
  'Панорама загружена': 'Panorama uploaded',
  // admin
  'Жалобы на продавцов и автоматические решения ИИ': 'Seller complaints and automatic AI decisions', 'Жалобы': 'Complaints',
  'Решения ИИ-модерации': 'AI moderation decisions', 'Жалоб нет': 'No complaints', 'Пока никто не жаловался на продавцов': 'No one has reported sellers yet',
  'Снять обвинения': 'Dismiss', 'Предупредить': 'Warn', 'Заблокировать': 'Ban', 'Разбанить': 'Unban', 'Разбан': 'Unban',
  'Решение применено': 'Decision applied', 'Разбанен': 'Unbanned', 'Решений нет': 'No decisions',
  'ИИ ещё не выносил решений по модерации': 'AI has not made moderation decisions yet', 'Без действий': 'No action',
  'Предупреждение': 'Warning', 'Блокировка': 'Ban', 'Обоснование ИИ': 'AI reasoning', 'Источник': 'Source', 'Дата': 'Date', 'админ': 'admin',
  // seller profile
  'Профиль не найден': 'Profile not found', 'Написать продавцу': 'Message seller', 'Объявления': 'Listings',
  'Нет объявлений': 'No listings', 'У продавца нет активных объектов в этой категории': 'The seller has no active listings in this category',
  'У продавца нет объектов для начала диалога': 'The seller has no listings to start a chat', 'Диалог откроется по одному из объектов продавца.': 'The chat opens on one of the seller listings.',
  'Подтверждён': 'Verified', 'Все объекты': 'All listings',
  // auth
  'С возвращением': 'Welcome back', 'Войдите, чтобы продолжить поиск жилья': 'Sign in to continue your home search',
  'Пароль': 'Password', 'Забыли пароль?': 'Forgot password?', 'Войти по коду из письма': 'Sign in with email code',
  'или': 'or', 'Создайте аккаунт': 'Create an account', 'Продавцы публикуют объекты сразу, без модерации': 'Sellers publish instantly, no moderation',
  'Я хочу': 'I want to', 'Ищу жильё': 'Find a home', 'Размещаю объекты': 'List properties', 'Создать аккаунт': 'Create account',
  'Минимум 6 символов': 'At least 6 characters', 'Аккаунт создан! Код отправлен на почту.': 'Account created! A code was emailed.',
  'Вход по коду': 'Code sign-in', 'Сброс пароля': 'Reset password', 'Сбросить пароль': 'Reset password', 'Отправить код': 'Send code',
  'Код отправлен': 'Code sent', 'Код отправлен на почту.': 'The code was sent to your email.', 'Код из письма': 'Code from email',
  'Не просто список квартир — решение, где жить': 'Not just listings — deciding where to live',
  'Ходите по квартире в 360°, спрашивайте ИИ прямо про зону на панораме, бронируйте онлайн и доверяйте честным отзывам.': 'Walk through a home in 360°, ask the AI about any zone, book online and trust honest reviews.',
  '360°-туры с навигацией между комнатами': '360° tours with room-to-room navigation',
  'Spatial Q&A — вопросы про конкретную зону': 'Spatial Q&A — questions about a specific zone',
  'ИИ-агент сам ищет и сравнивает объекты': 'The AI agent searches and compares for you',
  // misc / toasts / errors
  'Сохранить': 'Save', 'Отмена': 'Cancel', 'Подтвердить': 'Confirm', 'Ошибка': 'Error', 'Ошибка запроса': 'Request error',
  'Сеть недоступна. Проверьте подключение.': 'Network unavailable. Check your connection.', 'Удалено': 'Deleted',
  'Добавлено в избранное': 'Added to favorites', 'Удалено из избранного': 'Removed from favorites',
  'Войдите, чтобы продолжить': 'Sign in to continue', 'Войдите, чтобы задавать вопросы': 'Sign in to ask questions',
  'Страница не найдена': 'Page not found', 'На главную': 'Go home', 'Объекты на карте': 'Properties on map',
  'Карта недоступна': 'Map unavailable', 'Mapbox-токен не настроен. Объекты — в списке слева.': 'Mapbox token is not set. Listings are in the list on the left.',
  'Нет объектов по фильтрам': 'No properties match the filters', 'Слои на карте': 'Map layers', 'Метро': 'Metro',
  'Школы': 'Schools', 'Магазины': 'Shops', 'Метро ': 'Metro', 'Школа': 'School', 'Магазин': 'Shop', 'Подробнее': 'Details',
  'низкий': 'low', 'средний': 'medium', 'высокий': 'high', 'неизвестно': 'unknown',
  'м²': 'm²', 'комн.': 'rooms',
  'аренда': 'rent', 'продажа': 'sale', 'только что': 'just now', 'Объект': 'Property', 'Без имени ': 'No name',
  'Объект не найден ': 'Property not found', 'ИИ не настроен на сервере': 'AI is not configured on the server',
  '⚠️ ИИ не настроен на сервере (нет AI_API_KEY).': '⚠️ AI is not configured on the server (no AI_API_KEY).',
};

// Pattern rules for interpolated strings.
export const RULES = [
  [/^Найдено объектов: (.+)$/, 'Properties found: $1'],
  [/^Отзывы \((.+)\)$/, 'Reviews ($1)'],
  [/^Отзывов \((.+)\)$/, 'Reviews ($1)'],
  [/^(.+) жалоб$/, '$1 complaints'],
  [/^(.+) вопросов$/, '$1 questions'],
  [/^Объект #(.+)$/, 'Property #$1'],
  [/^Продавец #(.+)$/, 'Seller #$1'],
  [/^Комната (.+)$/, 'Room $1'],
  [/^(\d+) мин$/, '$1 min'],
  [/^(\d+) ч$/, '$1 h'],
  [/^(\d+) дн$/, '$1 d'],
  [/^(.+) комн\.$/, '$1 rooms'],
  [/^(.+) ноч\. × (.+) = (.+)$/, '$1 nights × $2 = $3'],
  [/^Бронирование — (.+)$/, 'Booking — $1'],
  [/^Аналитика — (.+)$/, 'Analytics — $1'],
  [/^Редактор 360°-тура — (.+)$/, '360° tour editor — $1'],
  [/^Написать: (.+)$/, 'Message: $1'],
  [/^Применить решение для продавца #(.+)\?$/, 'Apply decision for seller #$1?'],
  [/^DEV-код: (.+)$/, 'DEV code: $1'],
  [/^На Nestora с (.+)$/, 'On Nestora since $1'],
];
