"""initial schema

Revision ID: 6bfdbc947acc
Revises: 
Create Date: 2026-05-31 11:50:51.822710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfdbc947acc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infrastructure_pois', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infrastructure_pois_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructure_pois_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructure_pois_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_infrastructure_pois_lng'), ['lng'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('buyer', 'seller', 'admin', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'warned', 'banned', name='userstatus'), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('moderation_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('unfounded', 'warning', 'ban', name='moderationdecision'), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('overridden_by_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_decisions_seller_id'), ['seller_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('price_drop', 'new_message', 'booking_confirmed', 'recommendation', 'warning', 'ban', 'complaint_decision', name='notificationtype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('apartment', 'house', 'commercial', name='propertytype'), nullable=False),
    sa.Column('deal_type', sa.Enum('rent', 'sale', name='dealtype'), nullable=False),
    sa.Column('rent_term', sa.Enum('short', 'long', name='rentterm'), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'deleted', name='propertystatus'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_deal_type'), ['deal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_lng'), ['lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_type'), ['type'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_property_id'), ['property_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('payment_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_payment_token'), ['payment_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_renter_id'), ['renter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_seller_id'), ['seller_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'seller_id', 'property_id', name='uq_conversation_pair')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_seller_id'), ['seller_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_favorite_user_property')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('price_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('last_seen_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_tracker_user_property')
    )
    with op.batch_alter_table('price_trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_trackers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_trackers_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_trackers_user_id'), ['user_id'], unique=False)

    op.create_table('property_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('photo', 'pano', name='mediakind'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_media_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_media_property_id'), ['property_id'], unique=False)

    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requests_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_property_id'), ['property_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'user_id', name='uq_review_property_user')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('spatial_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=100), nullable=True),
    sa.Column('zone_coords', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spatial_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spatial_qa_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spatial_qa_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spatial_qa_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spatial_qa_user_id'), ['user_id'], unique=False)

    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tours_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tours_property_id'), ['property_id'], unique=True)

    op.create_table('viewing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viewing_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viewing_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_history_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewing_history_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_sessions_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_sessions_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_payment_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_payment_sessions_booking_id'))

    op.drop_table('payment_sessions')
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_is_read'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_id'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_conversation_id'))

    op.drop_table('direct_messages')
    with op.batch_alter_table('viewing_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewing_history_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_viewing_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_viewing_history_property_id'))
        batch_op.drop_index(batch_op.f('ix_viewing_history_id'))

    op.drop_table('viewing_history')
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tours_property_id'))
        batch_op.drop_index(batch_op.f('ix_tours_id'))

    op.drop_table('tours')
    with op.batch_alter_table('spatial_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spatial_qa_user_id'))
        batch_op.drop_index(batch_op.f('ix_spatial_qa_property_id'))
        batch_op.drop_index(batch_op.f('ix_spatial_qa_id'))
        batch_op.drop_index(batch_op.f('ix_spatial_qa_created_at'))

    op.drop_table('spatial_qa')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_property_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    op.drop_table('reviews')
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requests_property_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_buyer_id'))

    op.drop_table('purchase_requests')
    with op.batch_alter_table('property_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_media_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_media_id'))

    op.drop_table('property_media')
    with op.batch_alter_table('price_trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_trackers_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_trackers_property_id'))
        batch_op.drop_index(batch_op.f('ix_price_trackers_id'))

    op.drop_table('price_trackers')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_price_history_property_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_property_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_seller_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_property_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_buyer_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_seller_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_property_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_buyer_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_renter_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_property_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_payment_token'))
        batch_op.drop_index(batch_op.f('ix_bookings_payment_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))

    op.drop_table('bookings')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_property_id'))
        batch_op.drop_index(batch_op.f('ix_availability_id'))

    op.drop_table('availability')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_type'))
        batch_op.drop_index(batch_op.f('ix_properties_status'))
        batch_op.drop_index(batch_op.f('ix_properties_seller_id'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_lng'))
        batch_op.drop_index(batch_op.f('ix_properties_lat'))
        batch_op.drop_index(batch_op.f('ix_properties_id'))
        batch_op.drop_index(batch_op.f('ix_properties_deal_type'))
        batch_op.drop_index(batch_op.f('ix_properties_created_at'))
        batch_op.drop_index(batch_op.f('ix_properties_area'))

    op.drop_table('properties')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('moderation_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_decisions_seller_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_decisions_created_at'))

    op.drop_table('moderation_decisions')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_created_at'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('infrastructure_pois', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infrastructure_pois_lng'))
        batch_op.drop_index(batch_op.f('ix_infrastructure_pois_lat'))
        batch_op.drop_index(batch_op.f('ix_infrastructure_pois_kind'))
        batch_op.drop_index(batch_op.f('ix_infrastructure_pois_id'))

    op.drop_table('infrastructure_pois')
    # ### end Alembic commands ###
